<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curso [
    <!ELEMENT curso (nombre, alumno+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT alumno (nombreAlumno, apellidos)>
    <!ELEMENT nombreAlumno (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
]>

<curso>
    <nombre> </nombre>
    <alumno>
        <nombreAlumno></nombreAlumno>
        <apellidos></apellidos>
    </alumno>
    <alumno>
        <nombreAlumno></nombreAlumno>
        <apellidos></apellidos>
    </alumno>
</curso>